### ISSUE TITLE
Can Nuscene dataset be suitable for your model ?

### ISSUE THREAD

**Issue by RyanPham19092002** [tobiasfshr/map4d#11]
Hi,thanks for your great work!
I want to ask that what should I do to process and use Nuscene dataset for your model ?
Thanks for your help.

**Comment by tobiasfshr** [comment]
Hi, Nuscenes should be straightforward to use, but it requires writing a pre-process script as the ones here: https://github.com/tobiasfshr/map4d/blob/main/src/map4d/scripts/process_data.py

Note however to get best quality I would recommend to use the full 12 Hz images, which will be a bit tedious to deal with due to the different capturing frequencies of the cameras and the LiDAR + annotations. As far as I know, these are only synchronized at the mentioned 2Hz.

If you end up writing a pre-processing script for it, please feel free to make a PR! :)
