### ISSUE TITLE
Unable to process and train kitti sequences other than (0000, 0002, 0006)

### ISSUE THREAD

**Issue by jayaramreddy10** [tobiasfshr/map4d#18]
Hi, thanks for releasing the code. I have been trying to train for kitti sequences other than 0000, 0002, 0006 but I get the below issue. Is training and processing not supported for other kitti sequences? 

![Screenshot from 2024-11-12 14-22-22](https://github.com/user-attachments/assets/717396b4-7670-4df4-9453-53edb7ebe27d)

**Comment by tobiasfshr** [comment]
Hey, you can try it by modifying the data preprocessing code. We restrict it to the sequences mentioned because the benchmarks in prior work use only a subset of frames for training, and thus we need to map the frame ranges to each of the sequences defined in those benchmarks. You would need to remove this part of the code.
