### ISSUE TITLE
Want to render the video can see novel view like your video demo

### ISSUE THREAD

**Issue by RyanPham19092002** [tobiasfshr/map4d#9]
Hi ! Thanks to your great work
After I render novel view of your 4dgf model about waymo dataset, the outputs novel view are really good, but I want to render the video like your gif demo and using your model in the app (such as SIBR-viewer) to see novel view so how can I do that ? 

I used ns-view but the visualize is image below and I don't want this.
![image](https://github.com/user-attachments/assets/8825cd3d-8c65-42c6-83f7-d099ae4cf8e6)

P/s : I tried to convert output to gaussian-splatting by 
ns-export gaussian-splat 

But I have error : 
✅ Done loading checkpoint from outputs/waymo/4dgf-waymo/2024-09-03_092638/nerfstudio_models/step-000060000.ckpt
Traceback (most recent call last):
  File "/home/vinai/.conda/envs/map4d/bin/ns-export", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/vinai/.conda/envs/map4d/lib/python3.10/site-packages/nerfstudio/scripts/exporter.py", line 615, in entrypoint
    tyro.cli(Commands).main()
  File "/home/vinai/.conda/envs/map4d/lib/python3.10/site-packages/nerfstudio/scripts/exporter.py", line 537, in main
    assert isinstance(pipeline.model, SplatfactoModel)
AssertionError

Can your help me for this problem ? Thank you.

**Comment by tobiasfshr** [comment]
The usual 3DGS viewers will not work with our model because we don't use spherical harmonics as color representation, so we don't support the export of the models into PLY files. You could try to approximate this by querying the neural field from either a single (e.g. training view) direction and storing this color in the PLY file. Note that our demo is from a different model trained on multiple sequences of the Argoverse 2 dataset (residential split).

**Comment by RyanPham19092002** [comment]
Thank you so much for your help.
